ko = """백범 김구(한국 한자: 1876년 8월 29일 (음력 7월 11일) ~ 1949년 6월 26일)는 일제 강점기 독립 운동가이자 대한민국의 통일운동가, 정치인이다. 1949년 6월 26일 안두희에게 총살당하여 사망하였다.
대일 의열단체 한인애국단을 이끌었고 대한민국 임시정부 주석을 역임하였으며, 1962년 '건국훈장 대한민국장'이 추서되었다. 양반가의 후손으로 태어나 과거에 응시했으나 낙방, 이후 동학농민혁명에 참가했고, 한때 불교 승려로 활동했다.
자는 연하, 처음 이름은 창암이고, 호는 '백범', 연상이다. 호는 미천한 백성을 상징하는 백정의 ‘백’과 보통 사람이라는 범부의 ‘범’ 자를 따서 지었다. 19세 때 이름을 창수로 바꾸었다가, 36세(1912년)에 거북 '구'였던 이름을 아홉 '구'로 바꾸었다.
그 밖에 환속 이후의 이름인 두래, 피난 시기에 사용한 가명인 장진, 장진구도 있었다. 젊어서 동학교도였고, 불교에 귀의해서 법명 원종을 얻은 승려였으며, 28세 때 부친 탈상 후 기독교에 입문하였다.
양산학교, 보강학교 등에서 교육자로 교편을 잡기도 했고, 해서교육총회 학무총감으로도 활동했다. 교육·계몽 운동 중 일본 제국 경찰에 연행되어 수감되기도 하였다.
김방경의 25대손으로 본관은 구 안동이며, 황해도 해주 출신이다.
1919년 이후 상해에서 대한민국 임시정부에 참여하여, 의정원 의원, 경무국장, 내무총장, 국무총리 대리, 내무총장 겸 노동국 총판 등을 지냈다.
외교 중심의 독립 운동 성과를 얻지 못하자 1921년 임시 정부 내 노선 갈등 이후 일부 독립 운동가가 임시 정부를 이탈하고, 만주사변 이후에 일본의 중국 침략이 본격화되면서 중국 관내 여러 지역으로 임시 정부를 옮겨다녔으며, 1924년에는 만주 대한통의부 박희광 등을 통한 친일파 암살 및 주요공관 파괴, 군자금 모집 등을 비밀리에 지휘하였고, 1931년에 독립 운동 단체인 한인애국단을 조직하여 이봉창의 동경 의거, 윤봉길의 훙커우 공원 사건 등을 지휘하였다.
1926년 12월부터 1927년까지 1930년부터 1933년까지 임시정부 국무령을, 이후 국무위원, 내무장, 재무장 등을 거쳐 1940년 3월부터 1947년 3월 3일까지 임시정부 국무위원회 주석을 지냈다.
1945년 광복 이후에는 임시정부 법통 운동과, 이승만, 김성수 등과 함께 신탁 통치 반대 운동과 미소 공동위원회 반대 운동을 추진하였으며, 1948년 1월부터 남북 협상에 참여했다."""

en = """Baek Beom Kim Gu (Korean hanja: Baek Beom Kim; August 29, 1876 (July 11, 1876) - June 26, 1949) was a Korean independence activist, unificationist, and politician during the Japanese occupation of Korea.
He was shot dead by Ahn Doo-hee on June 26, 1949.
He led the Korean Patriotic Organization and served as a member of the Provisional Government of the Republic of Korea, and was awarded the Order of the Republic of Korea in 1962.
A descendant of a nobleman, he took the examination in the past but was rejected, participated in the Donghak Peasant Revolution, and was once a Buddhist monk. His first name was Changam, and his last name is Ho, a white beast.
Ho is a combination of Baekjeong, which symbolizes the lowly people, and Bum, which means common man. At the age of 19, he changed his name to Changsu, and at the age of 36 (1912), he changed his name from turtle 'gu' to nine 'gu'.
He also had Durae, his name after his reincarnation, and Jang Jin and Jang Jingu, pseudonyms he used during the evacuation.
As a young man, he was a student at the East School, a monk who returned to Buddhism and received the dharma name Wonjong, and at the age of 28, he entered Christianity after his father's death.
He taught as an educator at the Yangsan School and the Reinforcement School, and also served as secretary-general of the Haeju Education Conference. During the education and enlightenment movement, he was arrested and imprisoned by the Japanese Imperial Police.
The 25th generation grandson of Kim Bang-kyung, he was born in Andong, Hwanghae Province. After 1919, he participated in the Korean Provisional Government in Shanghai, serving as a member of the National Assembly, Director of Police, Minister of the Interior, Acting Prime Minister, Minister of the Interior, and General Manager of the Labor Bureau. As the diplomacy-oriented independence movement failed to achieve results, some independence activists left the provisional government in 1921 after a line conflict within the provisional government, and as Japan's invasion of China began in earnest after the Manchurian Incident, he moved the provisional government to various parts of China. In 1924, he secretly directed the assassination of pro-Japanese activists, the destruction of key government offices, and the recruitment of military funds through Park Hee-gwang of the Ministry of Korean Affairs in Manchuria, and in 1931, he organized the Korean Patriotic Corps, an independence movement group, and directed the events of Lee Bong-chang's Donghwa-dong and Yun Bong-gil's Hongkou Park. From December 1926 to 1927, he served as Secretary of State of the Provisional Government from 1930 to 1933, and later as State Councilor, Minister of the Interior, and Minister of Finance, and from March 1940 to March 3, 1947, he served as Chairman of the Provisional Government's State Council. After the liberation of Korea in 1945, he was involved in the movement for the rule of law in the Provisional Government and, together with Syngman Rhee and Kim Sung-soo, the movement against trusteeship and the movement against the Miso Joint Committee, and participated in the inter-Korean negotiations from January 1948."""